### ISSUE TITLE
Can u upload metrics-sampler-distribution-(version)-all with changes done on jmx connection file

### ISSUE THREAD

**Issue by Madhankumar1005** [dimovelev/metrics-sampler#11]

**Comment by dimovelev** [comment]
Hi, okay, I will release and it should be available in the next few days (it takes a while until it gets synced to maven central).

**Comment by dimovelev** [comment]
Released version 0.8.0 which also includes a memcached input. It should soon be available in maven central.

**Comment by dimovelev** [comment]
if you need it right away you can also fetch it directly from sona-type at https://oss.sonatype.org/service/local/repositories/releases/content/com/github/dimovelev/metrics-sampler-distribution/0.8.0/metrics-sampler-distribution-0.8.0-all.tar.gz

**Comment by Madhankumar1005** [comment]
Thanks for your Great Help
